<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-5EGJT544" name="firmLead_TechnicalInterview.LoginPage_LoginFunctionality" tests="7" failures="1" timestamp="2020-11-19T17:08:27 EST" time="4.651" errors="0">
  <testcase name="loginFunctionality_012_Email_TextBoxenable" time="0.406" classname="firmLead_TechnicalInterview.LoginPage_LoginFunctionality"/>
  <system-out/>
  <testcase name="loginFunctionality_013_Password_TextBoxEnable" time="0.420" classname="firmLead_TechnicalInterview.LoginPage_LoginFunctionality"/>
  <system-out/>
  <testcase name="loginFunctionality_014_ValidEmail_ValidPassword" time="0.769" classname="firmLead_TechnicalInterview.LoginPage_LoginFunctionality">
    <failure type="java.lang.AssertionError" message="did not expect [https://demo.combyne.ag/login] but found [https://demo.combyne.ag/login]">
      <![CDATA[java.lang.AssertionError: did not expect [https://demo.combyne.ag/login] but found [https://demo.combyne.ag/login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertNotEquals(Assert.java:1404)
at org.testng.Assert.assertNotEquals(Assert.java:1409)
at firmLead_TechnicalInterview.LoginPage_LoginFunctionality.loginFunctionality_014_ValidEmail_ValidPassword(LoginPage_LoginFunctionality.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginFunctionality_014_ValidEmail_ValidPassword -->
  <system-out/>
  <testcase name="loginFunctionality_015_InvalidEmail_ValidPassword" time="0.978" classname="firmLead_TechnicalInterview.LoginPage_LoginFunctionality"/>
  <system-out/>
  <testcase name="loginFunctionality_016_ValidEmail_InvalidPassword" time="0.665" classname="firmLead_TechnicalInterview.LoginPage_LoginFunctionality"/>
  <system-out/>
  <testcase name="loginFunctionality_017_NoEmail_NoPassword" time="0.799" classname="firmLead_TechnicalInterview.LoginPage_LoginFunctionality"/>
  <system-out/>
  <testcase name="loginFunctionality_018_InvalidEmail_InvalidPassword" time="0.614" classname="firmLead_TechnicalInterview.LoginPage_LoginFunctionality"/>
  <system-out/>
</testsuite> <!-- firmLead_TechnicalInterview.LoginPage_LoginFunctionality -->
